# -*- coding: utf-8 -*-
"""pixelImageManipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102yfZUSRfgBD_W7sDi2c3tQWrgfuwOOU
"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

def encrypt_image(image_path, key):
    img = Image.open(image_path).convert('RGB')
    data = np.array(img).astype(np.int16)

    encrypted_data = (data + key) % 256
    encrypted_img = Image.fromarray(encrypted_data.astype('uint8'))
    return encrypted_img

def decrypt_image(encrypted_img, key):
    data = np.array(encrypted_img).astype(np.int16)
    decrypted_data = (data - key) % 256
    decrypted_img = Image.fromarray(decrypted_data.astype('uint8'))
    return decrypted_img


while True:
    print("Press 1 to Encrypt, 2 to Decrypt, or any other key to Exit:")
    try:
        choice = int(input())
    except ValueError:
        print("Exiting...")
        break

    if choice == 1:
        print("🔐 Encryption")
        print("Upload image for encryption:")
        uploaded = files.upload()
        image_filename = list(uploaded.keys())[0]

        key = int(input("Enter an encryption key (0–255): "))
        encrypted = encrypt_image(image_filename, key)

        print("Encrypted image:")
        plt.imshow(encrypted)
        plt.axis('off')
        plt.show()

        encrypted.save("encrypted_image.png")
        print("Encrypted image saved as 'encrypted_image.png'")

    elif choice == 2:
        print("🔓 Decryption")
        print("Upload encrypted image for decryption:")
        uploaded = files.upload()
        image_filename = list(uploaded.keys())[0]

        key = int(input("Enter the decryption key (same as encryption key): "))
        encrypted = Image.open(image_filename)
        decrypted = decrypt_image(encrypted, key)

        print("Decrypted image:")
        plt.imshow(decrypted)
        plt.axis('off')
        plt.show()
    else:
        print("Exiting...")
        break